version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mailing_service_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=65mH6ftBQdZu
    restart: always
    networks:
      main:
        aliases:
          - db

  web:
    build:
      context: .
    env_file:
      - .env
    expose:
      - "8000"
    restart: "always"
    volumes:
      - static_volume:/app/staticfiles

    depends_on:
      - db
    networks:
      main:
        aliases:
          - web
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./config/nginx/conf.d/mailing_service.conf:/etc/nginx/conf.d/mailing_service.conf
    depends_on:
      - web
    networks:
      main:

networks:
  main:

volumes:
  postgres_db:
    driver: local
  static_volume: