version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mailing_service_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=65mH6ftBQdZu
    restart: always

volumes:
  postgres_db:
    driver: local