version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mailing_service_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=65mH6ftBQdZu
    restart: always
    networks:
      main:
        aliases:
          - db

  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: "always"

    depends_on:
      - db
    networks:
      main:
        aliases:
          - web
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

networks:
  main:

volumes:
  postgres_db:
    driver: local