# Generated by Django 5.0.3 on 2024-03-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_next_due_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='core.scheduler'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='time_of_day',
            field=models.TimeField(editable=False, help_text='Time of day to send the emails (HH:MM:SS format).'),
        ),
    ]
