# Generated by Django 5.0.3 on 2024-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduler_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='sent_times',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='time_of_day',
            field=models.TimeField(help_text='Time of day to send the emails (HH:MM:SS format).'),
        ),
    ]
